const NOW_PLAYING_ACTION_TYPE = 'NOW_PLAYING';
const POPULAR_ACTION_TYPE = 'POPULAR';
const TOP_RATED_ACTION_TYPE = 'TOP_RATED';
const UPCOMING_ACTION_TYPE = 'UPCOMING';

const actionsTypes = {
  NOW_PLAYING_ACTION_TYPE,
  POPULAR_ACTION_TYPE,
  TOP_RATED_ACTION_TYPE,
  UPCOMING_ACTION_TYPE,
};

export default actionsTypes;
